### ISSUE TITLE
Clarification on the readme. 

### ISSUE THREAD

**Issue by jdbertron** [zdenham/diamond-etherscan#6]
Can you explain what "Set the proxy implementation to point to the deployed dummy"  means ?
Is this a call on the diamond proxy contract to 'setDummyImplementation'  with the address of the dummy facet ?

**Comment by zdenham** [comment]
The way diamond etherscan works is it creates a dummy contract with all the signatures in your diamond. Its a "dummy" because none of the logic is actually implemented, its just function names for the sake of working with etherscan, which only supports a single proxy contract.

"Set the proxy implementation" refers to this standard: https://eips.ethereum.org/EIPS/eip-1967

Let me know if this clarifies things for you!

**Comment by jdbertron** [comment]
Yeah it did. Thank you. For someone else in the future, the dummy implementation is a separate contract that is not deployed as part of the diamond (because it would overwrite the methods and hardhat-deploy wouldn't let you do it anyway)
You deploy the DiamondEtherscan facet and LibDiamondEtherscan as part of the diamond. 
Then after your diamond has been deployed, you can set the implementation with something like this in the deployment script:
`    const setImplementationTx = await deployments.execute('BqETHDiamond',
      {from: deployer, log: true},
      'setDummyImplementation',dummyImplementation.address
    );`
    
The ERC-1967 interface will now point to a valid contract with all your methods, even though their actual implementation will still be in the facets, and callable through the diamond proxy's fallback. 
In order for Etherscan or AbiNinja to 'recognize' the contract, you will have to verify the dummyImplementation of course, so the tools know about your method signatures.
